### ISSUE TITLE
Find-Pixoo without success (Win11, PS 7.2.1)

### ISSUE THREAD

**Issue by bikeadventure** [quonic/PixooPS#1]
## Expected Behavior
I expected the command "Find-Pixoo" to identify the IP address...

## Current Behavior
...but the script runs through the address space without finding something:

PS C:\Users\peter> Find-Pixoo

Test-Connection: C:\Users\peter\Documents\PowerShell\Modules\PixooPS\0.3.0\Public\Find-Pixoo.ps1:44
Line |
  44 |  …             Test-Connection -Ping -Count 1 -TimeoutSeconds 1 -IPv4 -T …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Testing connection to computer '.1' failed: Cannot resolve the target name.

Test-Connection: C:\Users\peter\Documents\PowerShell\Modules\PixooPS\0.3.0\Public\Find-Pixoo.ps1:44
Line |
  44 |  …             Test-Connection -Ping -Count 1 -TimeoutSeconds 1 -IPv4 -T …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Testing connection to computer '.2' failed: Cannot resolve the target name.

==================
AND SO FORTH UNTIL .255:
==================

Test-Connection: C:\Users\peter\Documents\PowerShell\Modules\PixooPS\0.3.0\Public\Find-Pixoo.ps1:44
Line |
  44 |  …             Test-Connection -Ping -Count 1 -TimeoutSeconds 1 -IPv4 -T …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Testing connection to computer '.254' failed: Cannot resolve the target name.

Exception: C:\Users\peter\Documents\PowerShell\Modules\PixooPS\0.3.0\Public\Find-Pixoo.ps1:48
Line |
  48 |                      throw "Pixoo64 not found on network"
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Pixoo64 not found on network

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
None I guess. 

## Context
?

## Your Environment
I have Win11, tried it with pre-installed Powershell 5 in admin mode. Then installed Powershell 7 and tried again in admin mode.

**Comment by quonic** [comment]
What are the first 6 hexadecimal of your Pixoo's MAC address? Like for example mine starts with `7C-87-CE`.

**Comment by quonic** [comment]
Published a fix to the PowerShell Gallery that should fix this problem. It doesn't look for the MAC address any more.

Running `Find-Pixoo -IPAddress "Your Pixoo IP Address Here"` will skip the scanning and use that IP address, but if that address isn't the IP of the Pixoo then all other commands will fail.

```powershell
Install-Module PixooPS -Scope CurrentUser
```

**Comment by bikeadventure** [comment]
I uninstalled and installed. did not work. I restarted Powershell and ran Find-Pixoo -IPAddress "My Pixoo IP Address Here". Worked.

Running new Powershell with find-pixoo only stalls. CTRL-C then letting it know the IP like above works.

Never mind. I switched to programming it in Python, works :-)

**Comment by quonic** [comment]
> I uninstalled and installed. did not work. I restarted Powershell and ran Find-Pixoo -IPAddress "My Pixoo IP Address Here". Worked.

PowerShell sometimes needs the session refreshed when functions and cmdlets are updated.

> Running new Powershell with find-pixoo only stalls. CTRL-C then letting it know the IP like above works.

`Find-Pixoo` shouldn't stall, if you don't specify an IP address then it will try to connect to each computer on port 80. I've tried to speed this up, as a /24 network would take about 254 seconds to "scan" the entire network. The speed up can't output anything as Test-Connection doesn't work with a pipeline like I how I would like it to. There are ways to display a progress, but that adds a bit too much code complexity.

> Never mind. I switched to programming it in Python, works :-)

[https://github.com/virtualabs/pixoo-client/blob/main/pixoo.py#L25](https://github.com/virtualabs/pixoo-client/blob/main/pixoo.py#L25) and [https://github.com/SomethingWithComputers/pixoo/blob/main/pixoo/__init__.py#L66](https://github.com/SomethingWithComputers/pixoo/blob/main/pixoo/__init__.py#L66) don't look too have a function that finds the device automatically. One you have to specify the MAC and the other an IP address.

If the Pixoo used bonjour/mDNS or a consistent OUI for the MAC then it would be easier to find it.
